Fix build range build warning
- address
isotp_sf.c:136:29: error: comparison is always false
due to limited range of data type [-Werror=type-limits]

Signed-off-by: Greg Moffatt <greg.moffatt@gmail.com>